#!/bin/bash
#SBATCH --job-name=bn_v2
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=12  
#SBATCH --partition=intel_q
#SBATCH --account=birdnet
#SBATCH --time=4-00:00:00
#SBATCH --output=/projects/birdnet/chemours/birdnet_job_output/%x_%j.out

# Load pre-requisite module
module load site/tinkercliffs/easybuild/setup

# Load Miniconda3 module
module load Miniconda3/23.10.0-1

# Export the path for the conda environment that contains BirdNET-Analyzer v2.4
export BNENV=/projects/birdnet/env/tc/bna2.4-intel

# Activate the conda environment
source activate $BNENV

# Ensure necessary packages are installed
conda install -y numpy tensorflow librosa resampy

# Set directories for input and output in a '/projects/birdnet/' directory

#Where the recordings (.wav, .flac, .mp3) are located
IN_DIR=/projects/birdnet/chemours/data_2024/ 

#For the .txt files that will be generated by BirdNET
# Not to be confused with the output directory in the sbatch script that just provide info on the sbatch job
OUT_DIR=/projects/birdnet/chemours/data_2024_bn/ 

# Run BirdNET analysis and specify the location for recordings in latitude and longitude
date
python $BNENV/BirdNET-Analyzer/analyze.py --i $IN_DIR --o $OUT_DIR --lat 31.0429 --lon -81.9687 # Winokur, Georgia
date

# Deactivate the environment
conda deactivate